# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

name: python_lint.

on: [ push ]

jobs: 
  pylint_checking:
    runs-on: ubuntu-latest

    steps:
      - name: install-python-3.8
        run: apt-get install python3.8
