# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

name: python-lint.

on: [ push ]

jobs: 
  pylint_checking:
    runs-on: ubuntu-latest
    container:
      image: python:3.8

    steps:
      - name: install-pylint
        run: pip3 install pylint
      
      - name: check-code-by-pylint 
        run: pylint /code/*.py
        
